# Generated by Django 5.0 on 2023-12-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acumulado', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True)),
                ('periodo_fin', models.DateTimeField(blank=True, null=True)),
                ('objetivo_mensual', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('porcentaje_completado', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=15)),
                ('matricula', models.CharField(max_length=15)),
                ('vehiculo', models.CharField(choices=[('206', '206'), ('207', '207'), ('208 1.6 HDI', '208 1.6 HDI'), ('208 1.6 NAFTA', '208 1.6 NAFTA'), ('208 1.5 NAFTA', '208 1.5 NAFTA'), ('301 1.6 NAFTA', '301 1.6 NAFTA'), ('301 1.6 HDI', '301 1.6 HDI'), ('307', '307'), ('308', '308'), ('308GTI', '308GTI'), ('408', '408'), ('408 1.6 HDI', '408 1.6 HDI'), ('408 1.6 NAFTA', '408 1.6 NAFTA'), ('408 1.5 NAFTA', '408 1.5 NAFTA'), ('508', '508'), ('508 1.6 HDI', '508 1.6 HDI'), ('508 1.6 NAFTA', '508 1.6 NAFTA'), ('508 1.5 NAFTA', '508 1.5 NAFTA'), ('2008', '2008'), ('2008 1.6 HDI', '2008 1.6 HDI'), ('2008 1.6 NAFTA', '2008 1.6 NAFTA'), ('2008 1.5 NAFTA', '2008 1.5 NAFTA'), ('3008', '3008'), ('3008 1.6 HDI', '3008 1.6 HDI'), ('3008 1.6 NAFTA', '3008 1.6 NAFTA'), ('3008 1.5 NAFTA', '3008 1.5 NAFTA'), ('5008', '5008'), ('5008 1.6 HDI', '5008 1.6 HDI'), ('5008 1.6 NAFTA', '5008 1.6 NAFTA'), ('5008 1.5 NAFTA', '5008 1.5 NAFTA'), ('Partner', 'Partner'), ('Partner 1.6 HDI', 'Partner 1.6 HDI'), ('Partner 1.6 NAFTA', 'Partner 1.6 NAFTA'), ('Partner 1.5 NAFTA', 'Partner 1.5 NAFTA'), ('Expert', 'Expert'), ('Expert 1.6 HDI', 'Expert 1.6 HDI'), ('Expert 1.6 NAFTA', 'Expert 1.6 NAFTA'), ('Expert 1.5 NAFTA', 'Expert 1.5 NAFTA'), ('Boxer', 'Boxer'), ('Boxer 1.6 HDI', 'Boxer 1.6 HDI'), ('Boxer 1.6 NAFTA', 'Boxer 1.6 NAFTA'), ('Boxer 1.5 NAFTA', 'Boxer 1.5 NAFTA'), ('Seleccione un modelo', 'Seleccione un modelo')], default='seleccione un modelo', max_length=20)),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('garantia', models.BooleanField(default=False)),
                ('modifacado', models.DateTimeField(auto_now=True)),
                ('entrega', models.DateTimeField(blank=True, default=None, null=True)),
                ('mano_de_obra', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignado', 'asignado'), ('frenado', 'frenado'), ('presupuesto', 'presupuesto'), ('en espera', 'en espera'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('finalizado', 'finalizado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField(null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('estado_presupuesto', models.CharField(choices=[('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('enviado', 'enviado'), ('pendiente de envio', 'pendiente de envio')], default='pendiente de envio', max_length=20)),
                ('repuestos', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orden')),
            ],
        ),
    ]
