# Generated by Django 5.0 on 2023-12-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_orden_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='accounts',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='accounts',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
