# Generated by Django 5.0 on 2023-12-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_accounts_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='completo',
        ),
    ]
