# Generated by Django 5.0 on 2023-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_orden_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='anio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo',
            field=models.CharField(choices=[('206', '206'), ('207', '207'), ('208 1.6 HDI', '208 1.6 HDI'), ('208 1.6 NAFTA', '208 1.6 NAFTA'), ('208 1.5 NAFTA', '208 1.5 NAFTA'), ('301 1.6 NAFTA', '301 1.6 NAFTA'), ('301 1.6 HDI', '301 1.6 HDI'), ('307', '307'), ('308', '308'), ('308GTI', '308GTI'), ('408', '408'), ('408 1.6 HDI', '408 1.6 HDI'), ('408 1.6 NAFTA', '408 1.6 NAFTA'), ('408 1.5 NAFTA', '408 1.5 NAFTA'), ('508', '508'), ('508 1.6 HDI', '508 1.6 HDI'), ('508 1.6 NAFTA', '508 1.6 NAFTA'), ('508 1.5 NAFTA', '508 1.5 NAFTA'), ('2008', '2008'), ('2008 1.6 HDI', '2008 1.6 HDI'), ('2008 1.6 NAFTA', '2008 1.6 NAFTA'), ('2008 1.5 NAFTA', '2008 1.5 NAFTA'), ('3008', '3008'), ('3008 1.6 HDI', '3008 1.6 HDI'), ('3008 1.6 NAFTA', '3008 1.6 NAFTA'), ('3008 1.5 NAFTA', '3008 1.5 NAFTA'), ('5008', '5008'), ('5008 1.6 HDI', '5008 1.6 HDI'), ('5008 1.6 NAFTA', '5008 1.6 NAFTA'), ('5008 1.5 NAFTA', '5008 1.5 NAFTA'), ('Partner', 'Partner'), ('Partner 1.6 HDI', 'Partner 1.6 HDI'), ('Partner 1.6 NAFTA', 'Partner 1.6 NAFTA'), ('Partner 1.5 NAFTA', 'Partner 1.5 NAFTA'), ('Expert', 'Expert'), ('Expert 1.6 HDI', 'Expert 1.6 HDI'), ('Expert 1.6 NAFTA', 'Expert 1.6 NAFTA'), ('Expert 1.5 NAFTA', 'Expert 1.5 NAFTA'), ('Boxer', 'Boxer'), ('Boxer 1.6 HDI', 'Boxer 1.6 HDI'), ('Boxer 1.6 NAFTA', 'Boxer 1.6 NAFTA'), ('Boxer 1.5 NAFTA', 'Boxer 1.5 NAFTA'), ('Seleccione un modelo', 'Seleccione un modelo')], default='seleccione un modelo', max_length=20),
        ),
    ]
