# Generated by Django 5.0 on 2023-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orden_anio_orden_km_orden_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='estado_cliente',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
