# Generated by Django 5.0 on 2023-12-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_presupuesto_estado_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='estado_cliente',
        ),
    ]
