# Generated by Django 5.0 on 2023-12-24 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_presupuesto_estado_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
