# Generated by Django 5.0 on 2023-12-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_presupuesto_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='token_rechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
