# Generated by Django 5.0 on 2024-01-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_orden_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tecnico',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('asignado', 'asignado'), ('frenado', 'frenado'), ('presupuestado', 'presupuestado'), ('en espera', 'en espera'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('finalizado', 'finalizado')], default='pendiente', max_length=20),
        ),
    ]
