# Generated by Django 5.0 on 2024-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_orden_tecnico_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='intervencion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
