# Generated by Django 5.0 on 2024-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_tecnico_alter_orden_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='hora_asignada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
