# Generated by Django 5.0 on 2024-08-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_orden_hora_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
