# Generated by Django 5.0 on 2024-08-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_orden_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='tiempo_total',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
