# Generated by Django 5.0 on 2024-08-28 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_orden_timer_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_total',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
