# Generated by Django 5.0 on 2024-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_modifacado_orden_modificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='modificado',
            new_name='modifacado',
        ),
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ItemSolicitado',
        ),
    ]
