# Generated by Django 5.0 on 2024-08-28 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_modificado_orden_modifacado_orden_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.orden')),
            ],
        ),
    ]
