# Generated by Django 5.0 on 2024-08-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_itemsolicitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolicitado',
            name='cantidad',
        ),
    ]
