# Generated by Django 5.0 on 2024-08-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_itemsolicitado_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitado',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
    ]
