# Generated by Django 5.0 on 2024-08-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_itemsolicitado_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='progreso',
            field=models.FloatField(default=0),
        ),
    ]
