# Generated by Django 5.0 on 2024-08-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_orden_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('vehiculo', models.CharField(choices=[('206', '206'), ('207', '207'), ('208 1.6 HDI', '208 1.6 HDI'), ('208 1.6 NAFTA', '208 1.6 NAFTA'), ('208 1.5 NAFTA', '208 1.5 NAFTA'), ('301 1.6 NAFTA', '301 1.6 NAFTA'), ('301 1.6 HDI', '301 1.6 HDI'), ('307', '307'), ('308', '308'), ('308GTI', '308GTI'), ('408', '408'), ('408 1.6 HDI', '408 1.6 HDI'), ('408 1.6 NAFTA', '408 1.6 NAFTA'), ('408 1.5 NAFTA', '408 1.5 NAFTA'), ('508', '508'), ('508 1.6 HDI', '508 1.6 HDI'), ('508 1.6 NAFTA', '508 1.6 NAFTA'), ('508 1.5 NAFTA', '508 1.5 NAFTA'), ('2008', '2008'), ('2008 1.6 HDI', '2008 1.6 HDI'), ('2008 1.6 NAFTA', '2008 1.6 NAFTA'), ('2008 1.5 NAFTA', '2008 1.5 NAFTA'), ('3008', '3008'), ('3008 1.6 HDI', '3008 1.6 HDI'), ('3008 1.6 NAFTA', '3008 1.6 NAFTA'), ('3008 1.5 NAFTA', '3008 1.5 NAFTA'), ('5008', '5008'), ('5008 1.6 HDI', '5008 1.6 HDI'), ('5008 1.6 NAFTA', '5008 1.6 NAFTA'), ('5008 1.5 NAFTA', '5008 1.5 NAFTA'), ('Partner', 'Partner'), ('Partner 1.6 HDI', 'Partner 1.6 HDI'), ('Partner 1.6 NAFTA', 'Partner 1.6 NAFTA'), ('Partner 1.5 NAFTA', 'Partner 1.5 NAFTA'), ('Expert', 'Expert'), ('Expert 1.6 HDI', 'Expert 1.6 HDI'), ('Expert 1.6 NAFTA', 'Expert 1.6 NAFTA'), ('Expert 1.5 NAFTA', 'Expert 1.5 NAFTA'), ('Boxer', 'Boxer'), ('Boxer 1.6 HDI', 'Boxer 1.6 HDI'), ('Boxer 1.6 NAFTA', 'Boxer 1.6 NAFTA'), ('Boxer 1.5 NAFTA', 'Boxer 1.5 NAFTA'), ('Seleccione un modelo', 'Seleccione un modelo')], default='seleccione un modelo', max_length=20)),
                ('chasis', models.CharField(max_length=16, unique=True)),
                ('anio', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='base.cliente')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.auto'),
        ),
    ]
