# Generated by Django 5.0 on 2024-08-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_orden_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='matricula',
        ),
    ]
