# Generated by Django 5.0 on 2024-08-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_cliente_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='vehiculo',
        ),
        migrations.AlterField(
            model_name='auto',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
