# Generated by Django 5.0 on 2024-09-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_orden_cliente_remove_orden_garantia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('asignado', 'asignado'), ('en proceso', 'en proceso'), ('frenado', 'frenado'), ('presupuestado', 'presupuestado'), ('en espera', 'en espera'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('finalizado', 'finalizado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Planificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
