# Generated by Django 5.0 on 2024-09-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_orden_estado_planificador_recepcionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(blank=True, default='Comentarios aqui..', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('asignado', 'asignado'), ('pausado', 'pausado'), ('en progreso', 'en progreso'), ('frenado', 'frenado'), ('presupuestado', 'presupuestado'), ('en espera', 'en espera'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('finalizado', 'finalizado')], default='pendiente', max_length=20),
        ),
    ]
