# Generated by Django 5.0 on 2024-09-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_orden_descripcion_alter_orden_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalManoDeObra',
        ),
    ]
