# Generated by Django 5.0 on 2024-09-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_delete_totalmanodeobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
