# Generated by Django 5.0 on 2024-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_horasvendidaspormes'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasvendidaspormes',
            name='objetivo_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
