# Generated by Django 5.0 on 2024-09-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_horasvendidaspormes_objetivo_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='mano_de_obra_presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
