# Generated by Django 5.0 on 2024-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_orden_intervencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('asignado', 'asignado'), ('pausado', 'pausado'), ('en progreso', 'en progreso'), ('frenado', 'frenado'), ('presupuestado', 'presupuestado'), ('en espera', 'en espera'), ('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('finalizado', 'finalizado'), ('entregado', 'entregado')], default='pendiente', max_length=20),
        ),
    ]
